FROM angr/angr

RUN su angr -c "cd /home/angr/; git clone https://github.com/ucsb-seclab/BootStomp"

RUN su angr -c "cd /home/angr/angr-dev/ana; git checkout 94928f773661eaa5a6c2dec40dad199c70daedab"
RUN su angr -c "cd /home/angr/angr-dev/angr; git checkout 63db61e5d925355688e88dda00f8321c214d7df1"
RUN su angr -c "cd /home/angr/angr-dev/archinfo; git checkout 39a26e4cbd7b93ca1e73c76cf54cd2263b6f9285"
RUN su angr -c "cd /home/angr/angr-dev/cooldict; git checkout e33f0b737d65820dd7cce2609fe8e311389b5cf0"
RUN su angr -c "cd /home/angr/angr-dev/claripy; git checkout f848cfb52e871359f848ac3c074da22dd0cb70ef"
RUN su angr -c "cd /home/angr/angr-dev/cle; git checkout d0648fe86679c5d4b1e621d2128363b86f00aae2"
RUN su angr -c "cd /home/angr/angr-dev/idalink; git checkout ff16e289c998fced209d58ee282d3cd75db1e739"
RUN su angr -c "cd /home/angr/angr-dev/monkeyhex; git checkout b14a420e2f214bcd199980bb78f0c3fc5775c4a1"
RUN su angr -c "cd /home/angr/angr-dev/mulpyplexer; git checkout 223521120efc54751741005cc3b935ab7642cdbe"
RUN su angr -c "cd /home/angr/angr-dev/pyvex; git checkout 043338b3674aeade10df57ebed22ce8ee95c0613"
RUN su angr -c "cd /home/angr/angr-dev/simuvex; git checkout 8b9d1f44dfa6437c8476b57d67822209e9a3c1fa"
RUN su angr -c "cd /home/angr/angr-dev/superstruct; git checkout ff8c6aa89f9709895475b1de96864113db11e9ed"
RUN su angr -c "cd /home/angr/angr-dev/vex; git checkout 3a620e43ecc71cb9e5470995a45bbce4a600293f"

